#!/usr/bin/env ruby

require 'net/https'
require 'yaml'

# capture png file
tmpfile = "/tmp/image_upload#{$$}"
imagefile = ARGV[1]

if imagefile && File.exist?(imagefile) then
  ext = File.extname(imagefile)
  if ext == '.png' or ext == '.gif' or ext == '.jpeg' or ext == '.jpg' or ext == '.svg' or ext == '.pdf' or ext == '.psd' then
    system "cp \"#{imagefile}\" \"#{tmpfile}\""
  else
    system "sips -s format png \"#{imagefile}\" --out \"#{tmpfile}\""
  end
else
  system "screencapture -i \"#{tmpfile}\""
  if File.exist?(tmpfile) then
    pixelWidth  = `sips -g pixelWidth "#{tmpfile}" | awk '/:/ {print $2}'`
    pixelHeight = `sips -g pixelHeight "#{tmpfile}" | awk '/:/ {print $2}'`
    displayName = `sips -g profile "#{tmpfile}" | awk -F':' '/:/ {print $2}'`.strip

    displayProfile = nil
    YAML.load(`system_profiler SPDisplaysDataType`)["Graphics/Displays"].each do |key, display|
      if display["Displays"] then
        displayProfile = display["Displays"]["#{displayName}"]
      end
    end
    system "sips -s dpiWidth 72 -s dpiHeight 72 -z #{pixelHeight} #{pixelWidth} \"#{tmpfile}\""
  end
end

if !File.exist?(tmpfile) then
  exit
end

imagedata = File.read(tmpfile)
File.delete(tmpfile)

# upload
boundary = '----BOUNDARYBOUNDARY----'

HOST = 'direct.yabumi.cc'
CGI = '/api/images.txt'
UA   = 'YabumiUploaderForOSX/1.4 Gyazo/2.0'

data = <<EOF
--#{boundary}\r
content-disposition: form-data; name="imagedata"; filename="yabumi.cc"\r
\r
#{imagedata}\r
--#{boundary}--\r
EOF

header ={
  'Content-Length' => data.length.to_s,
  'Content-type' => "multipart/form-data; boundary=#{boundary}",
  'User-Agent' => UA
}

https = Net::HTTP.new(HOST,443)

https.use_ssl = true
res = https.post(CGI,data,header)
url = res.response.body
IO.popen("pbcopy","r+"){|io|
  io.write res.response['X-Yabumi-Image-Url']
  io.close
}
system "open #{url}"
