#!/usr/bin/env ruby

require 'net/http'

# capture png file
tmpfile = "/tmp/image_upload#{$$}"
imagefile = ARGV[1]

if imagefile && File.exist?(imagefile) then
  ext = File.extname(imagefile)
  if ext == '.png' or ext == '.gif' or ext == '.jpeg' or ext == '.jpg' or ext == '.svg' or ext == '.pdf' then
    system "cp \"#{imagefile}\" \"#{tmpfile}\""
  else
    system "sips -s format png \"#{imagefile}\" --out \"#{tmpfile}\""
  end
else
  system "screencapture -i \"#{tmpfile}\""
  if File.exist?(tmpfile) then
    system "sips -d profile --deleteColorManagementProperties \"#{tmpfile}\""  
    dpiWidth    = `sips -g dpiWidth "#{tmpfile}" | awk '/:/ {print $2}'`
    dpiHeight   = `sips -g dpiHeight "#{tmpfile}" | awk '/:/ {print $2}'`
    pixelWidth  = `sips -g pixelWidth "#{tmpfile}" | awk '/:/ {print $2}'`
    pixelHeight = `sips -g pixelHeight "#{tmpfile}" | awk '/:/ {print $2}'`
    if (dpiWidth.to_f > 72.0 and dpiHeight.to_f > 72.0) then
        width  =  pixelWidth.to_f * 72.0 / dpiWidth.to_f
        height =  pixelHeight.to_f* 72.0 / dpiHeight.to_f
        system "sips -s dpiWidth 72 -s dpiHeight 72 -z #{height} #{width} \"#{tmpfile}\""
    end
  end
end

if !File.exist?(tmpfile) then
  exit
end

imagedata = File.read(tmpfile)
File.delete(tmpfile)

# upload
boundary = '----BOUNDARYBOUNDARY----'

HOST = 'direct.yabumi.cc'
CGI = '/api/images.txt'
UA   = 'YabumiUploaderForOSX/1.0 Gyazo/2.0'

data = <<EOF
--#{boundary}\r
content-disposition: form-data; name="imagedata"; filename="yabumi.cc"\r
\r
#{imagedata}\r
--#{boundary}--\r
EOF

header ={
  'Content-Length' => data.length.to_s,
  'Content-type' => "multipart/form-data; boundary=#{boundary}",
  'User-Agent' => UA
}

Net::HTTP.start(HOST,443,:use_ssl => true){|http|
  res = http.post(CGI,data,header)
  url = res.response.body
  IO.popen("pbcopy","r+"){|io|
    io.write res.response['X-Yabumi-Image-Url']
    io.close
  }
  system "open #{url}"
}
